################################################################################
# PREFIXES
################################################################################
PREFIX ns:  <https://data.smartcitymadrid.es/ontology/parking#>
PREFIX ex:  <https://data.smartcitymadrid.es/id/parking/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

################################################################################
# QUERY 1 - First ten parkings (id, name and address) ordered by ascending id
## Retrieves the first ten parking resources, returning their identifier (ns:hasId), name (ns:hasName) and address (ns:hasAddress), ordered by the parking identifier in ascending order
################################################################################
SELECT ?id ?name ?street WHERE {
  ?p a schema:ParkingFacility ;
     dct:identifier ?id ;
     schema:name ?name ;
     schema:address ?pa .
  ?pa schema:streetAddress ?street .
     
}
ORDER BY ASC(?id)
LIMIT 10

################################################################################
# QUERY 2 - EMT parkings (true) with postal code
## Returns the first ten parking resources that are managed by EMT (ns:isEMTParking = true), including their postal code (ns:hasAreaCode) and identifier
################################################################################
SELECT ?id ?name ?pc ?emtParking 
WHERE {
  ?p a schema:ParkingFacility ;
     dct:identifier ?id ;
     schema:name ?name ;
        schema:address ?pa .
        ?pa schema:postalCode ?pc .
        
  ?p my:isEMTParking ?emtParking .
  FILTER(?emtParking = true)
}
ORDER BY xsd:integer(?id)
LIMIT 10
ORDER BY xsd:integer(?id)
LIMIT 10

################################################################################
# QUERY 3 - Total number of parkings, cities, regions and countries
################################################################################
SELECT ?nParkings ?numCities ?numRegions ?numCountries WHERE {
  { SELECT (COUNT(DISTINCT ?p) AS ?nParkings) WHERE { ?p a schema:ParkingFacility } }
  { SELECT (COUNT(DISTINCT ?c) AS ?numCities)  WHERE { ?c a schema:City } }
  { SELECT (COUNT(DISTINCT ?r) AS ?numRegions) WHERE { ?r a my:AutonomousCommunity } }
  { SELECT (COUNT(DISTINCT ?n) AS ?numCountries) WHERE { ?n a schema:Country } }
}

################################################################################
# QUERY 4 - Number of parkings whose address contains “plaza” (case-insensitive)
## Counts how many parking resources have an address (ns:hasAddress) containing the word “plaza”, ignoring case sensitivity
################################################################################
SELECT (COUNT(?p) AS ?nParkings)
WHERE {
  ?p a schema:ParkingFacility ;
     schema:address ?pa .
  ?pa schema:streetAddress ?address .
  FILTER(CONTAINS(LCASE(STR(?address)), "plaza"))
}

################################################################################
# QUERY 5 - name and long, lat
################################################################################
SELECT ?name ?long ?lat
WHERE {
  ?p a schema:ParkingFacility ;
     schema:name ?name ;
     geo:hasGeometry ?geom .
  ?geom geo:long ?long ;
        geo:lat  ?lat .
}
ORDER BY ASC(?name)
LIMIT 10

################################################################################
# QUERY 6 - name + awkt point
################################################################################
SELECT ?name ?wkt
WHERE {
  ?p a schema:ParkingFacility ;
     schema:name ?name ;
     geo:hasGeometry ?geom .
  ?geom geo:asWKT ?wkt .
}
ORDER BY ASC(?name)
LIMIT 10

